### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/kube-metrics-adapter#6]
> We don't have any tests yet. It probably makes sense with unit tests. As we make the code more "testable", this might also improve the quality

### TODO
- [x] Determine coverage of current codebase ( Integrate [coverall](https://coveralls.io/) )
- [ ] Set target coverage for the codebase
- [ ] Implement unit-tests in code with low coverage

https://github.com/mikkeloscar/kube-metrics-adapter/issues/9#issue-362541610

**Comment by arjunrn** [comment]
@muaazsaleem has added some tests and we can close this for now
